# Generated by Django 5.1.6 on 2025-02-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Ціна'),
            preserve_default=False,
        ),
    ]
